# Generated by Django 5.2.7 on 2025-10-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_menu_meal_mealrating_menulike_menumeal_surveyanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='meals',
            field=models.ManyToManyField(related_name='menus', through='api.MenuMeal', to='api.meal'),
        ),
    ]
